### ISSUE TITLE
Fusing UGPS and DVL is difficult (extension overwrites EK3_SRC1_POSXY and EK3_SRC1_VELXY)

### ISSUE THREAD

**Issue by clydemcqueen** [bluerobotics/BlueOS-Water-Linked-DVL#35]
I've been working on fusing data from the WL UGPS and WL DVL and I'm getting good results in simulation. However, I see that the DVL extension is setting EK3_SRC1_POSXY and EK3_SRC1_VELXY to 6 (ExternalNav) every time it starts up, which complicates field testing.

In my simulations, these settings produce nice fusion:
~~~
1	1	EK3_SRC1_POSXY	3	2	# GPS
1	1	EK3_SRC1_POSZ	1	2	# Baro
1	1	EK3_SRC1_VELXY	3	2	# GPS
1	1	EK3_SRC1_VELZ	0	2	# None
1	1	EK3_SRC1_YAW	1	2	# Compass
1	1	EK3_SRC2_POSXY	0	2	# None
1	1	EK3_SRC2_POSZ	0	2	# None
1	1	EK3_SRC2_VELXY	6	2	# ExternalNav
1	1	EK3_SRC2_VELZ	0	2	# None
1	1	EK3_SRC2_YAW	0	2	# None
1	1	EK3_SRC3_POSXY	0	2	# None
1	1	EK3_SRC3_POSZ	0	2	# None
1	1	EK3_SRC3_VELXY	0	2	# None
1	1	EK3_SRC3_VELZ	0	2	# None
1	1	EK3_SRC3_YAW	0	2	# None
1	1	EK3_SRC_OPTIONS	1	4	# FuseAllVelocities
~~~
These settings use the UGPS for POSXY, and then use both UGPS and DVL for VELXY, as the FuseAllVelocities bit is set.

The workaround is to start the extension, then go into QGC and undo the changes.

Another workaround is to flip SRC1 and SRC2, and use a Python script (or some other method) to send a `MAV_CMD_SET_EKF_SOURCE_SET` message to ArduSub after it boots up to make SRC2 the primary source set:
~~~
1	1	EK3_SRC1_POSXY	6	2	# ExternalNav
1	1	EK3_SRC1_POSZ	1	2	# Baro
1	1	EK3_SRC1_VELXY	6	2	# ExternalNav
1	1	EK3_SRC1_VELZ	0	2	# None
1	1	EK3_SRC1_YAW	1	2	# Compass
1	1	EK3_SRC2_POSXY	3	2	# GPS
1	1	EK3_SRC2_POSZ	1	2	# Baro
1	1	EK3_SRC2_VELXY	3	2	# GPS
1	1	EK3_SRC2_VELZ	0	2	# None
1	1	EK3_SRC2_YAW	1	2	# Compass
1	1	EK3_SRC3_POSXY	0	2	# None
1	1	EK3_SRC3_POSZ	0	2	# None
1	1	EK3_SRC3_VELXY	0	2	# None
1	1	EK3_SRC3_VELZ	0	2	# None
1	1	EK3_SRC3_YAW	0	2	# None
1	1	EK3_SRC_OPTIONS	1	4	# FuseAllVelocities
~~~

Both of these workarounds are complicated.

The current behavior provides a nice out-of-the-box experience for first-time DVL users, but perhaps there's some way to make this optional?

**Comment by Williangalvani** [comment]
hi @clydemcqueen. have you checked how these settings perform with UGPS disabled? I wonder if we could stick to one set alone.

Alternatively, we could either have a button to set the params, or only set new parameters if the vehicle has the firmware defaults set.

**Comment by clydemcqueen** [comment]
Hi @Williangalvani I just did the comparison in SITL and the fusion results look reasonable with the UGPS disabled: https://github.com/clydemcqueen/ardusub_localization/pull/2

We haven't had a chance to run this in the water yet. I wonder if WL or other WL customers may have opinions on this?

**Comment by Williangalvani** [comment]
I am unable to to use the dvl with no gps is POSXY and VELXY are set to GPS, unfortunately.

I'm thinking we can add two new buttons in the extension UI: "Load parameters for DVL" "Load parameters for DVL+GPS"

I tested on stable 4.1.1. but we do need to support stable at least for now.

**Comment by clydemcqueen** [comment]
How about a 3rd option for experts: "Do not change parameters"

**Comment by Williangalvani** [comment]
> How about a 3rd option for experts: "Do not change parameters"

well. that would just be a matter of not clicking any of the other buttons =P

**Comment by clydemcqueen** [comment]
Ah, of course, these are buttons, not "radio buttons." Perfect!

**Comment by pkmiles** [comment]
hi guys. I've been playing around with surface GPS (mRo Ublox M9N device) + Waterlinked DVL A50 combo. The goal being to get approximate lat/long while underwater based on a last GPS fix on the surface.... Also having the EK3_SRC1_POSXY overwrite problem. Set it to "GPS" only to have the DVL code reset it to ExternalNav.   

I'm not familiar with the code, bit is it as simple as having the DVL check this parameter before over writing it?  If someone had set it to GPS (non default) is there a reason the DVL code would want to set it to ExternalNav (the default)?

**Comment by clydemcqueen** [comment]
@pkmiles Good idea -- a simple fix. I'll take a crack at it. Would you be willing to test it?

Edit: Willian proposed this early on: "or only set new parameters if the vehicle has the firmware defaults set."

**Comment by clydemcqueen** [comment]
Getting parameter values is possible, but a bit trickier than I expected. Instead, I've drafted a PR with the buttons suggested by @Williangalvani 

Needs some CSS love + some testing.

**Comment by pkmiles** [comment]
Thanks @clydemcqueen and @Williangalvani . Happy to test whatever you guys come up with.
Also, another thought: the buttons you propose "Load params for DVL" and "Load params for DVL+GPS" - I'm assuming that's for blending underwater GPS (USBL)? 

In our use case we're only looking to use the surface GPS sensor to get an initial position, use the DVL for approximate locations while under water (ignore GPS once lost), and then return to GPS again on re-surfacing.  At this stage, with input from Tony White, the only change we're making to achieve this is EK3_SRC_POSXY = GPS.

I guess my point is that this different use case may take a different set of params?  What if we had a drop-down and Apply button and hold the parameter settings in a JSON file that could be added to / modified?  So power users could add to the JSON file to create a new DVL params config...

**Comment by clydemcqueen** [comment]
> Happy to test whatever you guys come up with.

Thanks!

> the buttons you propose "Load params for DVL" and "Load params for DVL+GPS" - I'm assuming that's for blending underwater GPS (USBL)?

Yes.

> In our use case we're only looking to use the surface GPS sensor to get an initial position, use the DVL for approximate locations while under water (ignore GPS once lost), and then return to GPS again on re-surfacing.

I think you'll need [source set switching](https://ardupilot.org/copter/docs/common-non-gps-to-gps.html) to do this: use source set 1 (SRC1) on the surface and use source set 2 (SRC2) while underwater. [Willian has a Lua script](https://williangalvani.github.io/ardupilot-kb/ArduSub/WIP/DVL-GPS%20integration.html) that senses when the GPS is producing good results and switches back/forth.

> What if we had a drop-down and Apply button and hold the parameter settings in a JSON file that could be added to / modified? So power users could add to the JSON file to create a new DVL params config...

In the current PR the default is to not set the SRC parameters at all, so a power user can set the parameters by hand and know they will not be changed. Perhaps a future PR can add file upload.
