### ISSUE TITLE
Bugs in mavlink2resthelper

### ISSUE THREAD

**Issue by R-Stokke** [bluerobotics/BlueOS-Water-Linked-DVL#5]
Discovered two bugs in the mavlink2resthelper.py file:

1. Import in line 1 references companionhelper, should be blueoshelper.

2. The GET requests in line 175 and 186 are failing due to incomplete paths, likely due to BlueOS using a newer mavlink2rest version. Can be fixed by adding the constant:
`PATH_PREFIX = "/vehicles/1/components/1/messages"`

And updating the aforementioned lines to:
`response = request(MAVLINK2REST_URL + '/mavlink' + PATH_PREFIX + path)`

Ideally the path prefix should allow for accessing different vehicle and components IDs, unsure how to best implement this.

**Comment by patrickelectric** [comment]
Hi @R-Stokke, the first issue is already fixed on the latest version of master branch. 
About the support of the latest version of BlueOS, that issue still exist.
The second one appears to still exist. Be free to send a pull request with the necessary corrections, we right now are without time for the following days.
For the vehicle ID, I would recommend for now to access it as argument with argparse.
